### ISSUE TITLE
webserver doesn't respect ui5-server's custom middleware mountpaths

### ISSUE THREAD

**Issue by vobu** [SAP/karma-ui5#125]
issue showcase: https://github.com/petermuessig/ui5-ecosystem-showcase/tree/feature/testing

when running tests on an application where `ui5-server` is equipped with custom middleware (specifically: proxy-functionality), the middlewares' mountpaths in `ui5.yaml` are not recognized by the (karma?) webserver and errors at mountpath-access 

example with  mountpath == `/proxy`:
calling `karma start` shows an error in the console: 

```console
WARN [web-server]: 404: /proxy/api/v1/latest?format=json
SyntaxError: Unexpected token N in JSON at position 0
```
because `/proxy` is not recognized as `ui5-server`'s custom middleware. 

excerpt `ui5.yaml`:
```
server:
  customMiddleware:
  - name: ui5-middleware-simpleproxy
    mountPath: /proxy
    afterMiddleware: compression
    configuration:
      baseUri: "https://latest-openui5.rikosjett.com"
```

excerpt `karma.conf.js`:
```
module.exports = function (config) {
    config.set({
        frameworks: ["ui5"],
        browsers: ["Chrome"]
    });
};
```
