### ISSUE TITLE
 Problem with loading a local library

### ISSUE THREAD

**Issue by AdrianDengusiak** [SAP/karma-ui5#367]
Hi, 

I'm using VSC and Fiori Tools to build my projects. Currently I have a main project and a custom ui5 library, which is used in the main one. Here's the full description of the issue: https://answers.sap.com/questions/13528468/reference-library-and-karma-config.html

Basically, when I run my testsuite or unitTest pages separately, the library is loaded correctly. When I run with Karma, I get an error. 

My workspace structure is:
- zui5lib
- zui5mainproejct
(separate projects)

Comparing to the attached link, I also tried to modify my karma.conf.js a bit and I end up with:
```
module.exports` = function (config) {
	config.set({
		frameworks: ["ui5"],
		basePath: "../",
		ui5: {
			// eslint-disable-next-line sap-no-hardcoded-url
			url: "https://sapui5.hana.ondemand.com/1.71.21",
			type: "application",
			mode: "html",
			configPath: "ui5.yaml",
			paths: {
				webapp: "zui5mainproject/webapp"
			},
			testpage: "zui5mainproject/webapp/test/testsuite.qunit.html"
		},

		browsers: ["Chrome"]
	});
};
```
 In the console I see some paths are loaded from the unitTests.qunit.html, which is a part of my test suite:
```
Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58 [unitTests.qunit.html] Device API logging initialized - DEVICE'

Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58.405800 URL prefixes set to: -  sap.ui.ModuleSystem'

Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58.406000   (default) : ../../resources/ -  sap.ui.ModuleSystem'

Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58.406100   'com/ui5/zui5mainproject' : ../../ -  sap.ui.ModuleSystem'

Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58.406199   'test/unit' : ./ -  sap.ui.ModuleSystem'

Chrome 95.0.4638.69 (Windows 10) ERROR
  Uncaught Error: failed to load 'com/ui5/zui5lib/types/CustomDateFormat.js' from ../../resources/com/ui5/zui5lib/types/CustomDateFormat.js: 404 - Not Found
  at zui5mainproject/webapp/resources/sap-ui-core.js:107:907

  Error: failed to load 'com/ui5/zui5lib/types/CustomDateFormat.js' from ../../resources/com/ui5/zui5lib/types/CustomDateFormat.js: 404 - Not Found
      at makeNestedError (zui5mainproject/webapp/resources/sap-ui-core.js:92:37)
```
I also have an entry in my ui5.yaml file, which should serve static resources from my workspace
 ```
name: fiori-tools-servestatic
          afterMiddleware: compression
          configuration:
              paths:
                  - path: /resources/com/ui5/zui5lib
                    src: c:\Users\***\Desktop\***\VSC Workspace\Common SAPUI5 Library\zui5lib\src\com\ui5\zui5lib
                    fallthrough: false

```
For some reason karma cannot resolve this route and my custom type cannot be loaded during the test execution. Each other case like launching tests outside karma, launching index.html is working fine.

How can I resolve this dependency? I feel like my ui5.yaml with servestatic middleware is not working at all.
