### ISSUE TITLE
"QUnit not found" when using fiori-tools-proxy for proxying the ui5 sources

### ISSUE THREAD

**Issue by Siolto** [SAP/karma-ui5#396]
When I try to use the [fiori-tools-proxy](https://npm.io/package/@sap/ux-ui5-tooling#ui5) for loading the ui5 sources from a different location and I start and test the application locally, everything runs fine.

As soon as I try to run my tests with karma-ui5 I receive following error:
``` shell
 Uncaught ReferenceError: QUnit is not defined
  at webapp/test/integration/opaTests.qunit.js:1:1

  ReferenceError: QUnit is not defined
      at webapp/test/integration/opaTests.qunit.js:1:1
```
My ui5.yaml:
``` yaml
specVersion: '2.6'
metadata:
  name: myApplication
type: application
server:
  customMiddleware:
    - name: fiori-tools-proxy
      afterMiddleware: compression
      configuration:
        ignoreCertError: false
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://sapui5.hana.ondemand.com/
```
My karma.conf.js: 
``` javascript
module.exports = function(config) {
  config.set({

    frameworks: ["ui5"],

    ui5: {
    },

    browsers: ["Chrome"]

  });
};
```

Once i remove the loading of the ui5 sources using the fiori-tools-proxy the tests also run with karma perfectly fine.
