### ISSUE TITLE
The paths defined in the ui5.yml is not detected automatically

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/karma-ui5#56]
Hi Colleague,

I am working on the migration of this plugin in SAP Successfactors.

I noticed the new version has imported some new configuration such as `type` and `paths`. And I found there is a method called `autoDetectType` which will scan the `ui5.yaml` in the module root path to get the module type. It is wonderful and I really like this.

I suppose that this auto detect mechanism would find the paths I defined in the .yaml file as well.  But so far it seems only reading the type property.

Here is the `ui5.yaml` in my module,

```yaml
specVersion: '0.1'
resources:
  configuration:
    paths:
      webapp: /src/main/uilib/sap/sf/todo/
metadata:
  name: au-todo-sap.sf.todo-web
type: application
```

Just wonder if this plugin can detect the paths defined in this way so that I don't need add the paths into karma configuration again.
